Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,22 +5,26 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
+    
     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
-    - name: Unzip Sources
+        
+    - name: Unzip Sources Forcibly
       run: |
-        unzip Shizasrc.zip -d project_folder
-        cd project_folder
-        chmod +x gradlew || true
+        unzip -o Shizasrc.zip -d project_folder || echo "Ignored symbols error"
+        
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@v4
+      
     - name: Build Jar File
       run: |
         cd project_folder
+        chmod +x gradlew || true
         if [ -f gradlew ]; then ./gradlew build --no-daemon; else gradle build --no-daemon; fi
+        
     - name: Upload Clean Jar
       uses: actions/upload-artifact@v4
       with:
